WIIS-11808
wiilog/wiistock pull request #1037
Opened 2024-09-26 13:15 UTC by BenjaminWiilog

2024-10-02 09:39 UTC, RomainBarot requested changes

2024-10-02 09:39 UTC, RomainBarot commented on src/Service/ProductionRequest/ProductionRequestService.php
> +            $destinationLocation = $productionRequest->getDestinationLocation();
ici le else n'est pas utile car tu redéfini une valeur que tu ne modifies pas

2024-10-02 09:39 UTC, RomainBarot commented on src/Service/ProductionRequest/ProductionRequestService.php
> +        $productionRequest->setDestinationLocation($destinationLocation);
du coup tu peux mettre le set dans le if

2024-10-02 09:39 UTC, RomainBarot commented on templates/production_request/modal/form.html.twig
> +                }],
il te manque le else de ta ternaire

2024-10-17 08:38 UTC, adrbounaderwiilog requested changes

2024-10-17 08:38 UTC, adrbounaderwiilog commented on src/Repository/ProductionRequestRepository.php
> +                            ->leftJoin('production_request.destinationLocation', 'location')
Ne pas nommer l'alias du join comme ça
On est dans le bloc order => il doit y avoir un prefix order_

2024-10-17 08:38 UTC, adrbounaderwiilog commented on src/Service/ProductionRequest/ProductionRequestService.php
> +            $destinationLocation = $data->get(FixedFieldEnum::destinationLocation->name) ? $locationRepository->find($data->get(FixedFieldEnum::destinationLocation->name)) : null;
Récupérer dans une variable $data->get(FixedFieldEnum::destinationLocation->name)

2024-10-21 07:52 UTC, merged