WIIS-11848
wiilog/wiistock pull request #1058
Opened 2024-10-08 15:08 UTC by BenjaminWiilog

2024-10-09 08:25 UTC, adrbounaderwiilog commented on tests/Service/DateTimeServiceTest.php
> +        var_dump(exec("ls ./cache"));
supprimer

2024-10-09 08:27 UTC, adrbounaderwiilog commented
ne pas utiliser `array()` mais plutôt `[]`

2024-10-09 08:27 UTC, adrbounaderwiilog commented on tests/Service/DateTimeServiceTest.php
> +    private function arrayWorkedPeriod() : array
Faire une constante plutot qu'une fonction

2024-10-09 08:27 UTC, adrbounaderwiilog commented on tests/Service/DateTimeServiceTest.php
> +    private function arrayWorkedPeriodEmpty() : array
Faire une constante plutot qu'une fonction

2024-10-09 08:30 UTC, adrbounaderwiilog commented on tests/Service/DateTimeServiceTest.php
> +            32400000,
pour toutes les valeurs comme ça utiliser convertDateIntervalToMilliseconds en lui passant un date interval lisible

2024-10-09 08:32 UTC, adrbounaderwiilog commented
Dans DateTimeServiceTest pourquoi ne pas avoir une fonction qui prend en param la date 1, date 2, les daysworked et les freeworkeddays + le test à faire ?
Chaque test se ressemblent mais avec ces valeurs en entrée de différente

2024-10-09 09:48 UTC, BenjaminWiilog commented on tests/Service/DateTimeServiceTest.php
> +            32400000,
je ne comprends pas ce que tu entend par lisible

2024-10-11 12:38 UTC, adrbounaderwiilog requested changes

2024-10-11 12:38 UTC, adrbounaderwiilog commented on tests/Service/DateTimeServiceTest.php
>  class DateTimeServiceTest extends KernelTestCase
Ordonner toutes les fonctions de test en premier et toutes les autres en public

2024-10-11 15:11 UTC, adrbounaderwiilog requested changes

2024-10-11 15:11 UTC, adrbounaderwiilog commented on src/Service/DateTimeService.php
> +            $nextDay = $workedDays->offsetGet($currentDayKey);
une ligne en doublons ? et je n'ai pas compris tu as juste renommé $nextDayKey -> $currentDayKey ?

2024-10-14 08:53 UTC, BenjaminWiilog commented on src/Service/DateTimeService.php
> +            $nextDay = $workedDays->offsetGet($currentDayKey);
oui je me suis trompé j'ai mis deux fois la même ligne dans la fonction. 
Oui concrètement, parce qu'en faite tu as initialisé une variable  $currentDayKey avec le jour courant et $nextDay avec le jour courant + 1. Et après tu modifie la date avec ce $nextDay. Sauf que le $currentDayKey n'est jamais modifié (ce que j'ai changé) et du coup $nextDay non plus. On boucle sur le même jour de la semaine jusqu'à en trouver un qui n'est pas férié.

2024-10-14 15:12 UTC, adrbounaderwiilog requested changes

2024-10-14 15:12 UTC, adrbounaderwiilog commented on tests/Service/DateTimeServiceTest.php
> +    private const localPathCacheDay = 'work-period';
Tous les const en majuscule avec des _ stp :D

2024-10-14 15:12 UTC, adrbounaderwiilog commented on tests/Service/DateTimeServiceTest.php
> +    private function createCacheWorkedPeriod(array $arrayWordedDay, array $arrayFreeDay): void
peux -tu organiser le fichier en mettant les tests en haut et les fonctions privées en bas, comme ça :
constantes
attributs
constructeur
fonctions publiques (donc les tests)
fonctions privées

2024-10-15 14:40 UTC, merged