WIIS-11994
wiilog/wiistock pull request #1082
Opened 2024-10-24 10:01 UTC by BenjaminWiilog

2024-11-04 10:50 UTC, BenjaminWiilog commented on src/Controller/Settings/SettingsController.php
> +                    && !preg_match("/^([0-9]{2,3}):([0-5]\d)$/",
Pour avoir deux erreurs différentes et que l'utilisateur sache le problème

2024-11-05 13:16 UTC, GregoireDolidonWiilog requested changes

2024-11-06 13:35 UTC, adrbounaderwiilog requested changes

2024-11-06 13:35 UTC, adrbounaderwiilog commented on assets/js/pages/settings/index.js
> +    initializeType();
Vérifier si c'est utile ? 
* supprimer la fonction si non et remplacer les moments ou c'est appelé par le contenu ?
* renommer la classe handling-type si c'est utile ?

2024-11-06 13:35 UTC, adrbounaderwiilog commented on templates/settings/fixed_field_elements.html.twig
> +                                additionalAttributes :[
espace avant le :

2024-11-06 13:35 UTC, adrbounaderwiilog commented on src/Controller/Settings/SettingsController.php
> +                                "elements" => $emergencyField ? Stream::from($emergencyField->getElements())
indentation ternaire

2024-11-06 13:35 UTC, adrbounaderwiilog commented on src/Controller/Settings/SettingsController.php
Enlever le json_encode en php pour les elements deliveryTypeSettings

2024-11-06 13:35 UTC, adrbounaderwiilog commented on templates/settings/production/parametrage_complet/champs_fixes.html.twig
> +{% include 'settings/fixed_field_elements.html.twig' with {
indenter + plus explicite sur les paramètres (rajouter le count des types de prod)

2024-11-06 13:35 UTC, adrbounaderwiilog commented on src/Controller/Settings/SettingsController.php
> +                ->keymap(fn(string $type, int $index) => [$type, $delayArray[$index]])
indentation + rajouter le static à la fonction fn

2024-11-06 13:35 UTC, adrbounaderwiilog commented on src/Controller/SelectController.php
> +        if($request->query->has('category')) {
ne pas mettre se if et renommer dans ton html category -> categoryType
+ mutualiser

2024-11-06 13:35 UTC, adrbounaderwiilog commented on src/Controller/SelectController.php
> +                "availableResults" => $typeRepository->countAvailableForSelect($category, ['alreadyDefinedTypes' => $alreadyDefinedTypes]),
vérifier si on en a vraiment besoin & voir si on peut l'éviter ?

2024-11-06 13:35 UTC, adrbounaderwiilog commented on src/Controller/SelectController.php
> +        }else {
supprimer ce else en mutualisant

2024-11-07 08:14 UTC, BenjaminWiilog commented on assets/js/pages/settings/index.js
> +    $('.new-type-association-button').on('click', function () {
tu peux me rappeler pourquoi mettre le namespace ?

2024-11-12 15:57 UTC, merged