WIIS-12077
wiilog/wiistock pull request #1108
Opened 2024-11-08 10:40 UTC by BenjaminWiilog

2024-11-12 09:47 UTC, GregoireDolidonWiilog requested changes

2024-11-12 09:47 UTC, GregoireDolidonWiilog commented on assets/js/pages/settings/users/users.js
> +function removeSecondaryMail(){
initRemoveSecondaryMails

2024-11-12 09:47 UTC, GregoireDolidonWiilog commented on templates/settings/utilisateurs/utilisateurs/form.html.twig
> +                    {% for i in range(secondary_emails | length + 1, 2)%} {# génère les nouveaux inputs email vide avec un maximum de 2 génération #}
commentaire en Anglais

2024-11-12 09:47 UTC, GregoireDolidonWiilog commented on templates/settings/utilisateurs/utilisateurs/form.html.twig
> +                    {% for i in range(secondary_emails | length + 1, 2)%} {# génère les nouveaux inputs email vide avec un maximum de 2 génération #}
faire une constante qui contient le nb max d'emails secondaires

2024-11-12 09:47 UTC, GregoireDolidonWiilog commented on templates/settings/utilisateurs/utilisateurs/form.html.twig
> +                        {{ form.hidden("moreThanTwoEmail", "") }}
Input inutile. Pourquoi faire un input et du JS juste pour mettre un d-none à l'initialisation de la modale ? Mets directement le d-none sur le bouton.

2024-11-12 09:47 UTC, GregoireDolidonWiilog commented on templates/settings/utilisateurs/utilisateurs/form.html.twig
> +                                {{ form.input('secondaryEmails', label, true, '', {
Ce n'est vraiment pas beau de faire deux boucles. Transforme pour n'en faire qu'une seule.

2024-11-13 14:17 UTC, adrbounaderwiilog commented on assets/js/pages/settings/users/users.js
> +    initRemoveSecondaryMails()
le `;`

2024-11-13 14:18 UTC, adrbounaderwiilog commented on assets/js/pages/settings/users/users.js
> +        const $inputEmail = $button.closest('.secondary-email').find('input[name=secondaryEmails]')
Ne pas oublier le `;`

2024-11-28 13:40 UTC, adrbounaderwiilog requested changes

2024-12-02 14:07 UTC, adrbounaderwiilog requested changes
Ajouter une protection contre des emails secondaire vide : j'ai enregistrer le form sans email seconaire et en valeur dans la colonne j'avais : `[""]`

2024-12-09 13:43 UTC, GregoireDolidonWiilog requested changes

2024-12-09 13:43 UTC, GregoireDolidonWiilog commented on templates/settings/utilisateurs/utilisateurs/form.html.twig
> +{% set max_secondary_mail = 2 %}
faire une constante en PHP et l'utiliser aussi dans le back

2024-12-09 13:43 UTC, GregoireDolidonWiilog commented on templates/settings/utilisateurs/utilisateurs/form.html.twig
> +                {% for i in range(1, max_secondary_mail)%} {# init new email input empty with a max of 2 input #}
pas de variable sur une lettre

2024-12-09 13:43 UTC, GregoireDolidonWiilog commented on templates/settings/utilisateurs/utilisateurs/form.html.twig
> +                    <div class="form-group secondary-email {{ secondary_emails[index_in_secondary_emails] is not defined ? "d-none"}}">
pas de snake_case en twig

2024-12-09 13:43 UTC, GregoireDolidonWiilog commented on src/Controller/Settings/UserController.php
> +            unset($secondaryEmails[$index]);
c'est pas beau, a remplacer par un Stream::explode->filter

2024-12-09 13:43 UTC, GregoireDolidonWiilog commented on src/Controller/Settings/UserController.php
> +                else{
elseif  directement

2024-12-09 13:43 UTC, GregoireDolidonWiilog commented on src/Controller/Settings/UserController.php
> +                        return $this->json([
throw new FormException(

2024-12-17 08:31 UTC, adrbounaderwiilog requested changes

2024-12-17 09:04 UTC, merged