WIIS-12122
wiilog/wiistock pull request #1141
Opened 2024-11-20 09:14 UTC by GregoireDolidonWiilog

2024-11-27 14:33 UTC, adrbounaderwiilog requested changes
faire du nettoyage dans `preparation-show.js` : il y a des fonctions sur les UL qui ne sont pas utilisées ?

2024-11-27 14:33 UTC, adrbounaderwiilog commented on assets/js/pages/arrival/show.js
* Ajouter un import du Form
* plusieurs fonctions qui ne sont pas utilisées, ni exportées, ni mises dans global --> à vérifier ce qu'il faut en faire ? à supprimé ou utiliser dans le html ? : `editRowArrivage` / `deleteRowArrivage` / `getCommentAndAddHisto`

2024-11-27 14:33 UTC, adrbounaderwiilog commented on assets/js/pages/pack/pack.js
> +import exportFile from "@app/utils";
* mettre le bon export car ici c'est invalide `import {exportFile} from "@app/utils";`
* A vérifier mais je crois qu'on peut supprimer le `global.exportFile = exportFile`, faut mettre l'import dans le js des demandes de prod juste ?

2024-11-27 14:33 UTC, adrbounaderwiilog commented on templates/pack/show.html.twig
supprimer `{{ encore_entry_script_tags('pack') }}` et mettre dans common les fonction qui sont utilisées ici si nécessaire

2024-11-27 14:33 UTC, adrbounaderwiilog commented on webpack.config.js
tu peux renommer "pack" / "pack.js" en "pack-index" / "index.js" stp

2024-11-27 14:33 UTC, adrbounaderwiilog commented on assets/js/pages/pack/show.js
enlever tous les exports
Si une fonction est utilisés dans d'autres fichiers js la mettre dans le common (comme getTrackingHistory)

2024-11-27 14:33 UTC, adrbounaderwiilog commented on src/Service/IOT/IOTService.php
> +        $frameIsValid = $this->vali64dateFrame($profile, $payload);
c'est une erreur ?

2024-11-28 09:59 UTC, GregoireDolidonWiilog commented on src/Service/IOT/IOTService.php
> +        $frameIsValid = $this->vali64dateFrame($profile, $payload);
oui 😢

2024-12-02 12:55 UTC, merged