WIIS-12127
wiilog/wiistock pull request #1189
Opened 2024-12-16 14:03 UTC by GregoireDolidonWiilog

WIIS-12127

2024-12-20 10:25 UTC, adrbounaderwiilog requested changes
Le dev n'a pas l'air de fonctionner :
* j'ai fait un groupage avec GROUP2012_1 et l'ul UL2012_1 puis un second GROUP2012_2 + UL2012_1 mais que des messages de succès de création de mouvement traça, je n'ai pas de modale de confirmation
* j'ai bien compilé le js
* et pour chaque groupage ça me crée un seul mouvement de traca au lieu de 2 (un pour le groupe puis un pour l'UL normalement)

2024-12-20 10:25 UTC, adrbounaderwiilog commented on src/Service/TrackingMovementService.php
> +        $groupIteration = $options['groupIteration'] ?? 1;
Pourquoi à 1 ?
Ca vient casser le fonctionnement de la ligne 499 non ? `$tracking->setGroupIteration($groupIteration ?: $group->getGroupIteration());`

2024-12-20 10:25 UTC, adrbounaderwiilog commented on src/Service/TrackingMovementService.php
> +    public function manageSplitPack(EntityManagerInterface $entityManager,
indentation des params

2024-12-26 17:37 UTC, adrbounaderwiilog requested changes
Toujours KO fonctionnellement, j'ai mis une vidéo dans la tâche

2024-12-27 10:50 UTC, GregoireDolidonWiilog commented
La vidéo ne montre pas un scénario de test pour cette tâche. Je mets en pièce jointe une vidéo du comportement attendu.

2025-01-08 08:39 UTC, adrbounaderwiilog requested changes

2025-01-08 08:39 UTC, adrbounaderwiilog commented on assets/js/pages/tracking-movement/tracking-movement.js
> +        case 'CONFIRM_CREATE_GROUP':
Pourquoi faire un swtch avec des clés pour définir les messages ici, alors que certains messages sont dans le php

2025-01-08 08:39 UTC, adrbounaderwiilog commented on src/Controller/Api/Mobile/TrackingMovementController.php
> +                    DateTime::createFromFormat("d/m/Y H:i:s", $data["date"])
plutot la méthode qui est dans le FormatService ?

2025-01-08 08:39 UTC, adrbounaderwiilog commented on src/Service/TrackingMovementService.php
> +                $isGroup = $pack && $pack->isGroup();
plutot `$pack?->isGroup()`
et récupérer aussi dans une variable le `$pack?->getGroup()`

2025-01-08 08:39 UTC, adrbounaderwiilog commented on src/Service/TrackingMovementService.php
>              foreach ($packCodes as $packCode) {
plutot faire un Stream plutot qu'un foreach ?

2025-01-08 08:39 UTC, adrbounaderwiilog commented on src/Service/TrackingMovementService.php
>              foreach ($packCodes as $packCode) {
Mais je comprends pas on arrete pas la boucle à la premiere erreur ? mais c'est la derniere erreur qui est remonté ?

2025-01-09 14:28 UTC, merged