WIIS-9545
wiilog/wiistock pull request #207
Opened 2023-04-17 15:41 UTC by LouiseDelauneyWiilog

2023-05-15 13:14 UTC, adrbounaderwiilog requested changes
Faire le merge avec test (pour la tâche WIIS-9709)
et faire le système de cache de zone par défaut dans le service d'emplacement

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Controller/Api/Mobile/MobileController.php
> +                "isDeliveryPoint" => (bool)$request->request->get('isDelivery'),
getBoolean plutot que (bool)

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Controller/Api/Mobile/TransportController.php
> +                "Label" => "Patient",
petit L

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Controller/Api/Mobile/TransportController.php
> +                "Description" => "Unités logistiques livrées chez un patient",
petit D

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/EmplacementDataService.php
> +                    ->addTemperatureRange($temperatureRangeRepository->find($allowedTemperatureId));
faire un findBy(['id' => ... ] plutot qu'un foreach

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/EmplacementDataService.php
> +                    ->addAllowedNature($naturesRepository->find($allowedNatureId));
faire un findBy(['id' => ... ] plutot qu'un foreach

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/EmplacementDataService.php
> +            ->setAllowedDeliveryTypes(isset($data['allowedDeliveryTypes']) ? $typeRepository->findBy(["id" => $data["allowedDeliveryTypes"]]) : [])
!empty plutot que isset

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/EmplacementDataService.php
> +            ->setAllowedCollectTypes(isset($data['allowedCollectTypes']) ? $typeRepository->findBy(["id" => $data["allowedCollectTypes"]]) : [])
!empty plutot que isset

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/EmplacementDataService.php
> +    public function createEmplacement(array $data, EntityManagerInterface $entityManager): Emplacement
plutot persistLocation (comme tu persist l'emplacement à la fin

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/EmplacementDataService.php
> +                "Label" => $label,
petit L

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/ImportService.php
> +            $location = $this->emplacementDataService->createEmplacement($data, $this->entityManager);
non pas ici remettre new Emplacement, comme c'est l'import d'emplacement

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/ImportService.php
> +                    "Label" => $data['emplacement'],
petit L

2023-05-15 13:14 UTC, adrbounaderwiilog commented on src/Service/ImportService.php
> +                //$this->entityManager->persist($location);
supprimer la ligne

2023-05-15 13:14 UTC, adrbounaderwiilog requested changes
Faire le merge avec test (pour la tâche WIIS-9709)
et faire le système de cache de zone par défaut dans le service d'emplacement

2023-06-12 14:51 UTC, GregoireDolidonWiilog commented on src/Service/EmplacementDataService.php
> +        $defaultZone = $zoneRepository->findOneBy(['name' => Zone::ACTIVITY_STANDARD_ZONE_NAME]);
- pour éviter les appelles en DB inutiles mettre cet appelle seulement aux endroit ou il est nécessaire ( après le ?? dans le if, et dans le else) 
- si un utilisateur modifie le nom de la zone "Activité Standard" il va y avoir un bug. Pour éviter cela, rendre impossible La modification du nom ce cette zone (dans le twig et le php).

2023-06-15 15:25 UTC, merged