WIIS-9654-2
wiilog/wiistock pull request #685
Opened 2024-02-28 12:40 UTC by RobinPluviaux

2024-03-07 10:24 UTC, adrbounaderwiilog requested changes

2024-03-07 10:30 UTC, adrbounaderwiilog commented on cypress/support/command/general.js
ne pas faire la sélection du menu via `.wii-icon-${menu}` (ligne 7 et 13)

2024-03-07 13:16 UTC, RobinPluviaux commented on cypress/e2e/addAndEditComponentsInReferentiel.js
> +import {uncaughtException} from "../support/utils";
J'ai pas trouvé comment faire sans TS.

J'ai essayé ça : https://stackoverflow.com/questions/74488552/cypress-import-modules-via-alias
Mais ça n'a pas marché

2024-03-07 13:23 UTC, RobinPluviaux commented on templates/arrivage/modalNewArrivage.html.twig
> +                                    selected: ((defaultLocation is defined and defaultLocation != null) or keptDropLocation) ? true : false,
C'est à dire ? Quel ternaire ? Et comment tu aurais fait ?

Si on veut garder la "location" on met location.label, ensuite s'il y a une "location" par défaut alors on la met, sinon rien.

2024-03-07 13:40 UTC, RobinPluviaux commented on templates/emplacement/index.html.twig
> +                                data-cy-name="new-location-button"
Du coup on garde data-cy-name, pour être plus précis ? Ou alors remplacer par id générique (id="newLocationButton") pour que wiistock puisse aussi en bénéficier ?

2024-03-07 13:41 UTC, RobinPluviaux commented on cypress.config.js
> +const {defineConfig} = require("cypress");
J'avais déjà essayé mais ça ne fonctionne pas. 
![image](https://github.com/wiilog/wiistock/assets/130456417/6b772829-d29a-4247-bc06-36083be3335b)

2024-03-07 15:23 UTC, RobinPluviaux commented on cypress/support/command/general.js
data-cy-menu

2024-03-25 14:53 UTC, RobinPluviaux commented on cypress/e2e/addAndEditComponentsInReferentiel.js
![Capture d’écran du 2024-03-25 15-52-49](https://github.com/wiilog/wiistock/assets/130456417/1bb72856-bb3f-4135-9c9c-9ada3c84025a)

2024-05-03 08:03 UTC, merged