WIIS-11203
wiilog/wiistock pull request #767
Opened 2024-03-29 09:32 UTC by RobinPluviaux

2024-04-02 14:51 UTC, GregoireDolidonWiilog requested changes

2024-04-02 14:51 UTC, GregoireDolidonWiilog commented on assets/js/pages/settings/statuses.js
> +        });
se resume en         $(`[name=${groupName}]:checked`).length

2024-04-02 14:51 UTC, GregoireDolidonWiilog commented on assets/js/pages/settings/statuses.js
> +    checkboxes.forEach(checkbox => checkbox.addEventListener('change', updateCheckboxes));
se resume en  $(`[name=${groupName}]:not(:checked)`).prop('disabled', checkedCount >= maxChecked);

2024-04-02 14:51 UTC, GregoireDolidonWiilog commented on assets/js/pages/settings/statuses.js
> +    function updateCheckboxes() {
ne pas définir de fonction dans une fonction

2024-04-02 14:51 UTC, GregoireDolidonWiilog commented on assets/js/pages/settings/statuses.js
> +        $passStatusAtPurchaseOrderGeneration.prop('disabled', Boolean(true));
true c'est déja un booleen, pas besoin de Boolean(true)

2024-04-02 14:51 UTC, GregoireDolidonWiilog commented on src/Controller/Settings/StatusController.php
> +                    "passStatusAtPurchaseOrderGeneration" => "<div class='checkbox-container'><input type='checkbox' name='passStatusAtPurchaseOrderGeneration' class='form-control data $passStatusAtP
ca aurait été mieux de le faire avec le formSevice

2024-04-02 14:51 UTC, GregoireDolidonWiilog commented on src/Entity/Statut.php
> +    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
nullable: false, options: ['default' => false])]

2024-04-03 08:36 UTC, adrbounaderwiilog requested changes

2024-04-03 08:36 UTC, adrbounaderwiilog commented on assets/js/pages/settings/statuses.js
> +    const excludedStateForPassStatusAtPurchaseOrderGeneration = ["0", "1"];
Trouver un moyen d'enlever ce tableau (pour de la lisibilité, 0 et 1 c'est pas parlant)
à la manière de data-need-mobile-sync-disabled=true dans StatusService::getStatusStatesOptions peut être

2024-04-04 07:52 UTC, adrbounaderwiilog requested changes

2024-04-04 07:52 UTC, adrbounaderwiilog commented on assets/js/pages/settings/statuses.js
> +            options :
pas besoin du options ? 
De toute facon on décoche, et on ne cache pas pour aligner le fonctionnement ? Ca ne casse rien pour l'utilisateur

2024-04-04 07:52 UTC, adrbounaderwiilog commented on assets/js/pages/settings/statuses.js
> +        if (options) {
A enlever ?

2024-04-04 07:52 UTC, adrbounaderwiilog commented on assets/js/pages/settings/statuses.js
> +    const fields = disabledFields.map(({name, disabled, options}) => ({
Pas besoin du map du coup on fait dans la même boucle la récup du champ  / passer en disable le champ

2024-04-09 15:10 UTC, merged