WIIS-11204
wiilog/wiistock pull request #781
Opened 2024-04-10 14:50 UTC by RobinPluviaux

2024-04-10 15:09 UTC, GregoireDolidonWiilog requested changes

2024-04-10 15:09 UTC, GregoireDolidonWiilog commented on src/Controller/PurchaseRequestController.php
> +    public function generatePurchaseOrder(PurchaseRequest           $purchaseRequest,
mettre un droit

2024-04-10 15:09 UTC, GregoireDolidonWiilog commented on src/Controller/PurchaseRequestController.php
> +    public function printDeliverySlip(Attachment      $attachment,
mettre un droit

2024-04-10 15:09 UTC, GregoireDolidonWiilog commented on src/Controller/PurchaseRequestController.php
> +    #[Route("/{purchaseRequest}/purchaseOrder/{attachment}", name:"print_purchase_order", options:["expose"=>true], methods:['GET'], condition: "request.isXmlHttpRequest()")]
self::GET

2024-04-10 15:09 UTC, GregoireDolidonWiilog commented on src/Entity/PurchaseRequest.php
> +use phpDocumentor\Reflection\Types\Boolean;
???

2024-04-10 15:09 UTC, GregoireDolidonWiilog commented on src/Service/PDFGeneratorService.php
> +
): string {

2024-04-10 15:09 UTC, GregoireDolidonWiilog commented on src/Service/PDFGeneratorService.php
> +        // todo: fill template
enlever le TODO

2024-04-10 15:09 UTC, GregoireDolidonWiilog commented on src/Service/PurchaseRequestService.php
> +        dump($variables);
ola

2024-04-11 07:34 UTC, RobinPluviaux commented on src/Entity/PurchaseRequest.php
> +use phpDocumentor\Reflection\Types\Boolean;
tkt

2024-04-11 07:35 UTC, RobinPluviaux commented on src/Service/PDFGeneratorService.php
> +
méthode plus utile, c'était un test

2024-04-11 07:36 UTC, GregoireDolidonWiilog requested changes

2024-04-11 07:36 UTC, GregoireDolidonWiilog commented on assets/js/pages/purchase-request/show.js
> +    console.log($button);
pas de  console.log

2024-04-11 07:36 UTC, GregoireDolidonWiilog commented on assets/js/pages/purchase-request/show.js
> +    AJAX.route(AJAX.GET, 'generate_purchase_order', {purchaseRequest: purchaseRequestId})
juste GET

2024-04-11 07:42 UTC, GregoireDolidonWiilog requested changes

2024-04-11 07:42 UTC, GregoireDolidonWiilog commented on src/Entity/ReferenceArticle.php
> +     * @return Collection<int, ArticleFournisseur>
Collection<int> ??

2024-04-11 07:42 UTC, GregoireDolidonWiilog commented on src/Service/PurchaseRequestService.php
> +            ->map(function (PurchaseRequestLine $line) {
static

2024-04-11 07:52 UTC, RobinPluviaux commented on src/Entity/ReferenceArticle.php
> +     * @return Collection<int, ArticleFournisseur>
Oui.
le int c'est la clé, pour clé valeur

2024-04-11 10:12 UTC, merged