WIIS-11258
wiilog/wiistock pull request #795
Opened 2024-04-24 10:08 UTC by RobinPluviaux

2024-04-24 12:37 UTC, GregoireDolidonWiilog requested changes

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Controller/Kiosk/KioskController.php
> +    #[Route("/delete/{kiosk}", name: "delete_kiosk", options: ["expose" => true], methods: self::DELETE, condition: 'request.isXmlHttpRequest()')]
chager les noms de routes pour qu'ils commencent par kiosk_

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on assets/js/pages/settings/kiosk.js
> +            type: `POST`
utiliser la constante POST de ajax.js

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Controller/Kiosk/KioskController.php
> +    #[Route("/delete/{kiosk}", name: "delete_kiosk", options: ["expose" => true], methods: self::DELETE, condition: 'request.isXmlHttpRequest()')]
(je suis contre cette pratique, cela nous est imposé par les bonnes pratiques de wiilog )

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Service/Kiosk/KioskService.php
> +                    "onclick" => "editRow($(this), Routing.generate('edit_kiosk_api', true), $(`#editKioskModal`), $('#editKioskSubmit'))"
mettre un onOpen() dans le form en js et utiliser modal.load

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Controller/Kiosk/KioskController.php
> +        $data = $request->request->all();
ne pas utiliser all() et recuperer la donnée depuis l'inputBag

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on templates/kiosk/modals/editKioskModal.html.twig
> +<div class="modal fade" id="editKioskModal" role="dialog" aria-labelledby="dataModalCenterTitle"
remplacer ce fichier par un include de emptyModal

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on templates/kiosk/modals/form.html.twig
> +            {% set settingCollectRequestType = setting_value('COLLECT_REQUEST_TYPE', 'App\\Entity\\Type') %}
pas les bonnes constantes

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on templates/kiosk/modals/form.html.twig
> +            {% set settingCollectRequestType = setting_value('COLLECT_REQUEST_TYPE', 'App\\Entity\\Type') %}
supprimer les constantes et faire une migration pour les enlever de la bdd

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on templates/kiosk/modals/form.html.twig
> +            {{ form.input(setting('COLLECT_REQUEST_ARTICLE_QUANTITY_TO_COLLECT'), "Quantité d'article à collecter", false, kiosk.quantityToPick ?? setting_value('COLLECT_REQUEST_ARTICLE_QUANTITY_TO_C
ca ce n'est plus valable car l'info ne dois plus etre dans la table setting : ?? setting_value('COLLECT_REQUEST_ARTICLE_QUANTITY_TO_COLLECT')

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on templates/settings/stock/borne_tactile/demande_collecte_et_creation_reference.html.twig
> +{% include 'kiosk/modals/editKioskModal.html.twig' %}
les includes des modal ce font en bas des fichiers (bonnes pratiques)

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Controller/Kiosk/KioskController.php
> +    #[Route("/check-is-valid", name: "check_article_is_valid", options: ["expose" => true], methods: [self::GET, self::POST])]
ne mettre q'une methode

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Entity/Setting.php
> +    const COLLECT_KIOSK_NAME = 'COLLECT_KIOSK_NAME';
ce n'est pas le bon fichier pour mettre cette constante

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Controller/Kiosk/KioskController.php
> +    #[Route('/api', name: 'kiosk_api', options: ['expose' => true], methods: 'POST', condition: 'request.isXmlHttpRequest()')]
methods: [self::POST],

2024-04-24 12:37 UTC, GregoireDolidonWiilog commented on src/Service/Kiosk/KioskService.php
> +            [
pourquoi ne pas le mettre dans getActionsConfig() ?

2024-04-24 13:11 UTC, RobinPluviaux commented on src/Controller/Kiosk/KioskController.php
> +    #[Route("/delete/{kiosk}", name: "delete_kiosk", options: ["expose" => true], methods: self::DELETE, condition: 'request.isXmlHttpRequest()')]
Pas ouf ouf certaine route on plus de sens avec ce nommage...

2024-04-25 13:47 UTC, GregoireDolidonWiilog requested changes

2024-04-25 13:47 UTC, GregoireDolidonWiilog commented on templates/kiosk/modals/form.html.twig
> +                type: 'collectType',
ne pas répeter ```constant(...)```
```twig
{% set field = constant('App\\Entity\\Fields\\FixedFieldEnum::type') %}
{{ form.select(field.name, field.value, true, {})
```

2024-04-25 13:51 UTC, merged