WIIS-11301
wiilog/wiistock pull request #796
Opened 2024-04-25 09:47 UTC by NunoMoreiraRibeiroWiilog

2024-04-30 08:42 UTC, ThomasGentileWiilog requested changes
A revoir

2024-04-30 08:42 UTC, ThomasGentileWiilog commented on src/Service/AttachmentService.php
> +                                                 EntityManagerInterface $entityManager)
Typer le retour (void)

2024-05-07 11:57 UTC, adrbounaderwiilog requested changes

2024-05-07 11:57 UTC, adrbounaderwiilog commented on src/Service/AttachmentService.php
> +    public function persistAttachments(AttachmentContainer $attachmentContainer,
Possible de fusionner les deux méthodes ?

2024-05-07 11:57 UTC, adrbounaderwiilog commented on src/Service/AttachmentService.php
> +    public function persistAttachments(AttachmentContainer $attachmentContainer,
Possible d'éviter les flush dans les méthodes nommées "persist" ? 
Comme ça c'est uniquement celui qui appelle la méthode qui décide si il flush ou pas

2024-05-07 11:57 UTC, adrbounaderwiilog commented on src/Service/AttachmentService.php
> +    public function persistAttachments(AttachmentContainer $attachmentContainer,
Aligner les arguments de la méthode

2024-05-07 11:57 UTC, adrbounaderwiilog commented on src/Controller/HandlingController.php
> +        $attachmentService->persistAttachments($handling, $request->files, $entityManager);
ajouter un flush après ?

2024-05-07 11:57 UTC, adrbounaderwiilog commented on src/Controller/TrackingMovementController.php
> +                $freeFieldService->manageFreeFields($mouvement, $post->all(), $entityManager, $this->getUser());
Tu as déplacé le manageFreeFields dans le if (isset($fileBag)) donc on ne touche pas aux champs libres si on n'a pas de pièce jointe ?

2024-05-15 14:51 UTC, adrbounaderwiilog requested changes
+ Appliquer l'appareil photo sur les litiges de réception

2024-05-15 14:51 UTC, adrbounaderwiilog commented on assets/js/pages/reception/show.js
> +        .onOpen(() => {
Non ne pas faire ça 
tu crées un Form mais tu l'utilises seulement pour le onOpen ici
Soit on crée un form et on supprime le initModal soit s'adapte à initModal

2024-05-16 13:15 UTC, GregoireDolidonWiilog requested changes

2024-05-16 13:15 UTC, GregoireDolidonWiilog commented on public/js/pages/arrival/index.js
> +    $modal.on('shown.bs.modal', function () {
ne pas mettre dans une event listener, cette fonction est deja lancé a l'ouverture de la modal

2024-05-16 13:15 UTC, GregoireDolidonWiilog commented on public/js/pages/arrival/show.js
> +    modal.on('shown.bs.modal', function () {
mettre un .off ici pour eviter de declarer plusieurs fois l'evenenement

2024-05-16 13:15 UTC, GregoireDolidonWiilog commented on public/js/pages/litiges.js
> +    Form
pas de form ici

2024-05-16 13:41 UTC, merged