WIIS-11415
wiilog/wiistock pull request #845
Opened 2024-05-28 13:42 UTC by NunoMoreiraRibeiroWiilog

2024-05-29 10:05 UTC, GregoireDolidonWiilog requested changes

2024-05-29 10:05 UTC, GregoireDolidonWiilog commented on cypress/e2e/production/01_createNewProductionRequest.js
> +        cy.get(selectorModal).should('be.visible', { timeout: 8000 }).then(() => {
il est basé sur quoi le time out ?

2024-05-29 10:05 UTC, GregoireDolidonWiilog commented on cypress/e2e/production/02_editProductionRequest.js
> +                    if(key !== "Date de création" && key !== "Date attendue"){
ce test ne permet pas de verifier si un champ est afficher un non dans le detail

2024-05-29 10:13 UTC, NunoMoreiraRibeiroWiilog commented on cypress/e2e/production/01_createNewProductionRequest.js
> +        cy.get(selectorModal).should('be.visible', { timeout: 8000 }).then(() => {
Valeur arbitraire

2024-06-03 15:07 UTC, adrbounaderwiilog requested changes
* est ce que tu as fait un test d'accès à la page de détails et vérifier que c'est bien la bonne page si on clique sur une ligne du datatable
* tu testes bien la page de liste ? ou c'est un test qui est fait à la création et la modif  ?

2024-06-04 08:12 UTC, NunoMoreiraRibeiroWiilog commented on cypress/e2e/production/01_createNewProductionRequest.js
> +            //TODO : Voir Pourquoi shouldWait doit être à false pour type le wait ne récupère pas la réponse.
Je dois voir avec Robin

2024-06-04 08:12 UTC, NunoMoreiraRibeiroWiilog commented on cypress/e2e/production/01_createNewProductionRequest.js
> +            //TODO voir pour la date par rapport au format de l'utilisateur.
Je dois voir avec Robin

2024-06-06 08:36 UTC, RobinPluviaux requested changes

2024-06-06 08:36 UTC, RobinPluviaux commented on templates/header.html.twig
> +                                       data-cy-request-item="colllecte">
Ya 3 l, et tout mettre en anglais serait mieux je pense

2024-06-06 08:36 UTC, RobinPluviaux commented on templates/header.html.twig
> +                                       data-cy-request-item="achat">
tout mettre en anglais serait mieux je pense

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/support/command/select2.js
> +                    .wait(1000)
il sert a quoi ce wait ?

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/support/command/general.js
> +
ajoute de la js doc

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/support/command/general.js
> +            cy.wait(1000);
t'es sur que tu es obligé de faire un .then pour mttre le wait ?

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/support/command/general.js
> +Cypress.Commands.add('fillFreeFields', (freeFields) => {
js doc

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/support/command/general.js
> +                    case 'input':
découpe ton code pour faire une méthode par case

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/support/command/general.js
> +                        if ($inputOrSelect.attr('type') === 'checkbox' || $inputOrSelect.attr('type') === 'radio') {
essaie de minifier le nombre d'imbrication de if

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/01_createProductionRequest.js
> +
tu dois ajouter "uncaughtException();" sur chaque page sinon avec les nouvelles images les actions GH vont crash

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/01_createProductionRequest.js
> +        cy.get('#modalNewProductionRequest').should('be.visible', { timeout: 8000 });
fait une constante de "modalNewProductionRequest" elle est utilisé 5x dans ce fichier

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/01_createProductionRequest.js
> +            yesNo: 'Oui',
ne pas mettre de string pour un yesNO utiliser un boolean

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/01_createProductionRequest.js
> +            cy.get('.ql-editor')
faire une méthode pour remplir les champs commentaire

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/01_createProductionRequest.js
> +            cy.get('input[type=file]')
faire une méthode pour les inputs de type file prcq ça évite de dupliquer du code

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/01_createProductionRequest.js
> +            cy.closeAndVerifyModal(selectorModal, 'submitNewProductionRequest', 'production_new',true);
espace

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/02_datatableProductionRequest.js
> +describe('Verify if the datatable of production requests work', () => {
"Verify if the datatable of production requests work" soit plus précis qu'est-ce que tu entends par "work" ? Que testes tu réellement

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/02_datatableProductionRequest.js
> +        cy.get('table#tableProductions tbody tr')
utiliser une constante pour "tableProductions"

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/02_datatableProductionRequest.js
> +            .eq(1)
C'est quoi ce magic number ? Le mettre dans une constante ou trouver un autre moyen de prendre la ligne

2024-06-06 08:36 UTC, RobinPluviaux commented on cypress/e2e/production/02_datatableProductionRequest.js
> +        cy.get('table#tableProductions tbody tr')
"cy.get('table#tableProductions tbody tr')
.first()
.find('td')
.eq(1)"

ces 3 lignes sont communes avec le block du dessus, tu peux essayer d'éviter de les répéter ?

2024-06-06 08:57 UTC, RobinPluviaux requested changes

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('#tableProductions_filter').should('be.visible', {timeout: 8000}).then((div) => {
Faire une méthode pour faire ça, ça peut être réutilisé 
Voir si tu peux pas directement aller sur la page via l'URL 
Le premier passage tu test le filtre et les fois suivante tu passes direct via l'url ?

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('table#tableProductions tbody tr')
encore du code commun avec un retour précédent, faire une méthode locale ? Attention évite un max les magic number

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('#modalEditProductionRequest').should('be.visible', { timeout: 8000 }).then(() => {
extriare une var "modalEditProductionRequest"

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +            cy.get('#modalEditProductionRequest .ql-editor')
utiliser la méthode que tu auras créé sur un autre ticket

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('.comment-container')
faire une méthode pour vérifier les commentaires

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        const inProgress = "En cours";
créer un fichier pour stocker ce genre de constante, ça peut être utile à plein d'endroit, plutôt que de les écrires en bruts à chaque fois

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('#modalUpdateProductionRequestStatus').should('be.visible', { timeout: 8000 }).then(() => {
créer une var

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +            cy.get('.timeline')
faire une méthode car peut être réutilisé ?

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        const toTreat = "A Traiter";
mettre dans le fichier crée dans l'autre ticket précédent

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('#modalUpdateProductionRequestStatus').should('be.visible', { timeout: 8000 }).then(() => {
mettre dans une constante

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +            cy.get('.timeline')
utiliser la méthode créé précédement

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        const processed = "Traité";
mettre dans le fichier la const

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('#modalUpdateProductionRequestStatus').should('be.visible', { timeout: 8000 }).then(() => {
créer une constante

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +            cy.get('.timeline')
pareil

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +            cy.contains('.wii-field-name', key).parents('div.row').first().within(() => {
ajoute un peu de commentaire pour que le code soit compris par le maximum de monde et saute des lignes après les .

.parents
.first() 
...

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +            yesNo: 'Oui',
utiliser un boolean*

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/03_editProductionRequest.js
> +            cy.contains('.wii-field-name', key).parents('.flex-column').within(() => {
ajoute un peu de commentaire

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +        cy.get('#tableProductions_filter').should('be.visible', {timeout: 8000}).then((div) => {
utiliser la méthode que tu auras crée précédement

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +        cy.get('table#tableProductions tbody tr')
crée une constante "tableProductions"

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +            .eq(1)
évite les magic number

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +            .eq(1)
pareil

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +        cy.get('.dropright.dropdown')
est-ce que c'est possible d'être extrait pour être réutilisé ?

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +        cy.get("#confirmation-modal")
créer une fonction réutilisable pour check l'input dans les modal de confirmations ?

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +        cy.get('#tableProductions_filter').should('be.visible', {timeout: 8000}).then((div) => {
utiliser la méthode faites précédement

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/04_deleteProductionRequest.js
> +        cy.get('#tableProductions')
faire une méthode car réutilisable

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +            'yesNo': 'Non',
utiliser une boolean

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +            'Pièces jointes': 'Oui',
boolean

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +        cy.get(`div.production-request-card-column[data-date=${expectedAt}]`).find('a.planning-card')
commente ce que tu essaies de faire

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +        const inProgress = "En cours";
met dans le fichier

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +        cy.get('#modalUpdateProductionRequestStatus').should('be.visible', {timeout: 8000}).then(() => {
faire une const "modalUpdateProductionRequestStatus"

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +        cy.get(`div.production-request-card-column[data-date=${expectedAt}]`).find('a.planning-card')
mettre à la ligne les .

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +                    .find('div.open-modal-update-production-request-status')
mettre dans une constante tu l'utilises plein de fois

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +        cy.get('#modalUpdateProductionRequestStatus').should('be.visible', {timeout: 8000}).then(() => {
faire une constante :"modalUpdateProductionRequestStatus"

2024-06-06 08:57 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +        cy.get(`div.production-request-card-column[data-date=${expectedAt}]`).find('a.planning-card')
faire une constante

2024-06-06 09:59 UTC, NunoMoreiraRibeiroWiilog commented on cypress/e2e/production/01_createProductionRequest.js
> +        cy.get('#modalNewProductionRequest').should('be.visible', { timeout: 8000 });
On peut mettre le selecteur dans une constante mais pas le get sinon on perd l'indépendance des tests

2024-06-06 11:34 UTC, NunoMoreiraRibeiroWiilog commented on cypress/e2e/production/02_datatableProductionRequest.js
> +        cy.get('table#tableProductions tbody tr')
Ce n'est pas possible

2024-06-06 12:59 UTC, NunoMoreiraRibeiroWiilog commented on cypress/e2e/production/03_editProductionRequest.js
> +        cy.get('table#tableProductions tbody tr')
J'ai testé et il n'est pas possible de stocker un bout du cypress dans une constante ou alias

2024-06-06 14:38 UTC, NunoMoreiraRibeiroWiilog commented on cypress/e2e/production/04_deleteProductionRequest.js
> +        cy.get('.dropright.dropdown')
Oui

2024-06-07 13:33 UTC, RobinPluviaux commented on cypress/e2e/production/05_planningProductionRequest.js
> +            // Utilisation d'un string et non d'un booleen car la carte contient un string pour indiquer s'il y a une pièce jointe où non.
Du coup la il y a que 2 valeurs possible ? Donc mettre un boolean ?

2024-06-07 13:33 UTC, RobinPluviaux commented on cypress/support/command/general.js
> +function fillInputsRadioCheckbox($input, value){
Certaines méthodes peuvent être déplacer dans des fichiers plus adéquat, il existe un fichier de modal, de datatable etc, pas obliger de tout mettre dans les méthodes général

Sinon tout le reste c'est good, merci pour la js doc

2024-06-07 14:07 UTC, NunoMoreiraRibeiroWiilog commented on cypress/support/command/general.js
> +function fillInputsRadioCheckbox($input, value){
Ça marche pas de souci

2024-06-10 07:23 UTC, merged