WIIS-11517
wiilog/wiistock pull request #873
Opened 2024-06-13 13:55 UTC by cedricrouxwiilog

WIIS-11517

2024-06-17 10:03 UTC, adrbounaderwiilog requested changes
dans article.js brancher le togglePrintButton dans le drawCallback (importé de util.js)

2024-06-17 10:03 UTC, adrbounaderwiilog commented on templates/article/index.html.twig
> +                                    id="printButton"
changer tous les printButton en class du coup, si par malheur il y en a plusieurs dans la page ça sera ok

2024-06-17 10:03 UTC, adrbounaderwiilog commented on assets/js/pages/reference-article/index.js
> +    $printTag = $('#printButton');
supprimer et brancher le meme système sur cette page aussi ?

2024-06-17 10:47 UTC, cedricrouxwiilog commented on templates/article/index.html.twig
> +                                    id="printButton"
ok

2024-06-17 15:22 UTC, cedricrouxwiilog commented on assets/js/datatable.js
> +        if (datatable.search() === '' || datatable.rows().count() === 0) {
ok

2024-06-17 15:22 UTC, cedricrouxwiilog commented on assets/js/datatable.js
> +function togglePrintButton(datatable) {
ok

2024-06-17 15:23 UTC, cedricrouxwiilog commented on assets/js/pages/reference-article/index.js
> +    $printTag = $('#printButton');
ok

2024-06-18 09:08 UTC, adrbounaderwiilog requested changes

2024-06-18 09:08 UTC, adrbounaderwiilog commented on assets/js/pages/article/article.js
attention certaines fonctions sont utilisées dans le html => elles sont pas exporter donc ça bug. Faire un Ctrl-shif-F pour voir si c'est utilisé.
clearNewArticleContent() serait à supprimer car pas utilisées par contre

2024-06-18 09:08 UTC, adrbounaderwiilog commented on webpack.config.js
> +    .addEntry('article', './assets/js/pages/article/article.js')
nommer article-index plutot, ne pas importer ce js dans les pages de show et edit

2024-06-18 09:08 UTC, adrbounaderwiilog commented on assets/js/pages/article/article.js
> +import {togglePrintButton} from "@app/utils";
importer AJAX aussi

2024-06-18 14:18 UTC, merged