WIIS-11610 && WISS-11608
wiilog/wiistock pull request #921
Opened 2024-07-18 14:40 UTC by GregoireDolidonWiilog

2024-07-22 12:27 UTC, RobinPluviaux commented
Mettre une default value à 1 ? : ![image](https://github.com/user-attachments/assets/ef4ad539-21bd-4e07-90f0-6631f810d8c1)

2024-07-22 13:12 UTC, RobinPluviaux requested changes

2024-07-22 13:12 UTC, RobinPluviaux commented on src/Service/AttachmentService.php
> +        if ($deleteTmpFile) {
t'es sur que c'est le bon nom de variable $deleteTMpFile alors que on fait un move ?

2024-07-22 13:12 UTC, RobinPluviaux commented on templates/production_request/modal/duplicate.html.twig
> +                    max: 10,
valeur par défaut de 1

2024-07-24 08:17 UTC, GregoireDolidonWiilog commented on src/Controller/ProductionRequest/ProductionRequestController.php
> +        foreach ($productionRequests as $productionRequest) {
Non, c'est mieux de tout flush en une seule fois, et on veut envoyer les mails seulement si le flush passe.

2024-07-24 08:25 UTC, GregoireDolidonWiilog commented on src/Service/AttachmentService.php
> +        if ($deleteTmpFile) {
Oui, car l'action de déplacer le fichier le supprime du répertoire des fichiers temporaires.

2024-07-24 12:23 UTC, merged