WIIS-11670
wiilog/wiistock pull request #922
Opened 2024-07-22 08:44 UTC by RobinPluviaux

2024-07-26 07:53 UTC, adrbounaderwiilog requested changes

2024-07-26 07:53 UTC, adrbounaderwiilog commented on assets/js/warningHeaderMessage.js
Remplace par du jquery stp

2024-07-26 07:53 UTC, adrbounaderwiilog commented on assets/js/warningHeaderMessage.js
> +        document.cookie = `${cookieName}=true`;
Je ne sais pas  comment ça marche mais faut pas mettre document.cookie += ?

2024-07-26 07:53 UTC, adrbounaderwiilog commented on src/Command/ToggleWarningHeaderMessageCommand.php
> +    public function __construct()
supprimer

2024-07-26 07:53 UTC, adrbounaderwiilog commented on templates/warning_header_message.html.twig
> +    {% if setting_value('WARNING_HEADER_MESSAGE') is not empty %}
mettre dans une variable

2024-07-26 07:53 UTC, adrbounaderwiilog commented on templates/warning_header_message.html.twig
> +{% block warning_mep_message %}
pas fan du block, normalement on l'utilise quand on extends le template avec un autre template

2024-07-26 07:53 UTC, adrbounaderwiilog commented on assets/js/warningHeaderMessage.js
avec des - le nom du fichier

2024-07-26 07:53 UTC, adrbounaderwiilog commented on src/DataFixtures/SettingFixtures.php
> +            Setting::WARNING_HEADER_MESSAGE => [
ne faire qu'un seul setting WARNING_HEADER au format json : soit vide soit un objet avec color et message
L'un de peut pas exister sans l'autre

2024-07-26 08:03 UTC, adrbounaderwiilog requested changes

2024-07-29 07:57 UTC, RobinPluviaux commented on assets/js/warningHeaderMessage.js
> +        document.cookie = `${cookieName}=true`;
Faut faire comme j'ai fait apparement

2024-07-30 08:05 UTC, adrbounaderwiilog requested changes

2024-07-30 08:05 UTC, adrbounaderwiilog commented on src/Command/WarningMessageSetCommand.php
> +namespace App\Command;
Sous namespace

2024-07-30 08:05 UTC, adrbounaderwiilog commented on src/Command/WarningMessageSetCommand.php
> +    public EntityManagerInterface $entityManager;
Dans le constructeur en private readonly plutot :)

2024-07-30 08:05 UTC, adrbounaderwiilog commented on src/Command/WarningMessageSetCommand.php
> +        $settingMessage = $settingRepository->findOneBy(['label' => Setting::WARNING_HEADER]);
SettingService::getSetting plutot

2024-07-30 08:05 UTC, adrbounaderwiilog commented on templates/warning_header_message.html.twig
> +{% set color_warning_header_message = warning_header and warning_header.color is not empty ? warning_header.color : false %}
supprimer les _message

2024-07-30 08:05 UTC, adrbounaderwiilog commented on templates/warning_header_message.html.twig
> +    {% if color_warning_header_message %}
pas mettre d'indentation + ajouter un `and message_warning_header̀

2024-07-31 13:18 UTC, merged