WIIS-11595
wiilog/wiistock pull request #923
Opened 2024-07-22 12:19 UTC by adrbounaderwiilog

2024-07-22 14:59 UTC, RobinPluviaux commented
BUGs : 
- Pendant l'import erreur sur le flush ![image](https://github.com/user-attachments/assets/174e3054-0696-43de-9de3-cd886a46c34d)

2024-07-25 08:45 UTC, RobinPluviaux requested changes

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/PurchaseRequestPlanController.php
> +            ->setCreatedAt(new \DateTime('now'));
faut importer datetime

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/PurchaseRequestPlanController.php
> +    #[Route('/{purchaseRequestPlan}/delete', name: 'purchase_request_plan_delete', options: ['expose' => true], methods: ['DELETE'], condition: 'request.isXmlHttpRequest()')]
self::delete

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/PurchaseRequestPlanController.php
> +                           PurchaseRequestPlan    $purchaseRequestPlan): Response {
jsonresponse

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/Settings/DataExportController.php
>      #[Route("/export/api", name: "settings_export_api", options: ["expose" => true], methods: "POST")]
self::post

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/Settings/DataExportController.php
> +                        EntityManagerInterface $entityManager): Response {
jsonResponse

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/Settings/DataExportController.php
>                          DataExportService      $dataExportService): Response {
jsonResponse

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/Settings/DataExportController.php
>      #[Route("/export/plannifie/{export}/annuler", name: "settings_export_cancel", options: ["expose" => true], methods: "GET|POST", condition: "request.isXmlHttpRequest()")]
self::POST

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/Settings/DataExportController.php
> +        if ($exportType?->getLabel() == Type::LABEL_SCHEDULED_EXPORT
met la condition dans une variable

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/Settings/ImportController.php
> +                                EntityManagerInterface $entityManager): Response {
jsonResponse

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/Settings/SettingsController.php
> +                                      InvMissionService      $invMissionService): Response {
jsonResponse

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Controller/ZoneController.php
> +        $purchaseRequestCounter = Stream::from($purchaseRequestPlanRepository->findAll())
pareil pas fan du findAll

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Entity/Inventory/InventoryMission.php
> +    private ?InventoryMissionPlan $creator = null;
Je trouve ça bizarre que un InventoryMissionnPlan soit nommé "creator" moi ça me fait penser à un utilisateur

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Entity/ScheduledTask/PurchaseRequestPlan.php
> +    #[ORM\Column(type: 'integer')]
Types::INTEGER

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Entity/ScheduledTask/ScheduleRule.php
> +    #[ORM\Column(type: 'integer')]
pareil

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Repository/ScheduledTask/ExportRepository.php
> +    private function createScheduledQueryBuilder(): QueryBuilder {
tu peux le mettre dans l'interface aussi ?

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Service/PurchaseRequestPlanService.php
> +    public function treatRequestPlan(EntityManagerInterface $entityManager,
tu as une injection d'un manager donc peut être la supprimer pour garder que celle ci

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Service/ScheduleRuleService.php
> +            $secondInHour = 60 * 60;
tu peux mettre 3600 directement ça évite un calcul inutile

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Service/ScheduleRuleService.php
> +            $secondsInDay = 60 * 60 * 24;
tu peux mettre la valeur en dur je pense, ou alors utiliser des constantes poiur stocker ces valeurs

2024-07-25 08:45 UTC, RobinPluviaux commented on templates/planner/frequencies/monthly.html.twig
> +                items: [1, 15, lastDayIndex] | map((day) => ({
mettre dans des constantes 1 et 15 et les utiliser aussi en back

2024-07-25 08:45 UTC, RobinPluviaux commented on src/Entity/ScheduledTask/ScheduledTask.php
> +    private ?DateTime $lastRun = null;
Types::DATETIME

2024-07-25 08:54 UTC, adrbounaderwiilog commented on src/Controller/InventoryMissionPlanController.php
> +                'requester' => $missionPlan->getRequester(),
Comme ça le twig fait passer peut utiliser comme il veut l'entité utilisateur

2024-07-25 08:55 UTC, adrbounaderwiilog commented on src/Controller/PurchaseRequestPlanController.php
> +        $data = Stream::from($purchaseRequestPlanRepository->findAll())
C'est ce qui était fait avant, faut modifier le fonctionnel si et rajouter une colonne, à voir plutard

2024-07-25 14:09 UTC, adrbounaderwiilog commented on assets/js/pages/settings/inventory/inventoryPlanner.js
> +    const missionPlan = $button.data('id');
Comme discuter, c'est un bug s'il est défini donc autant laisser comme ça si le bug remonte

2024-07-25 14:10 UTC, adrbounaderwiilog commented on assets/js/pages/settings/purchase-request/planner.js
> +                purchaseRequestPlan: $(this).data('id')
Comme discuté, c'est un bug s'il est non défini donc autant laisser comme ça si le bug arrive ça plantera

2024-07-25 14:18 UTC, adrbounaderwiilog commented on src/Controller/ZoneController.php
> +        $purchaseRequestCounter = Stream::from($purchaseRequestPlanRepository->findAll())
yen a max 10 donc c'est ok

2024-07-25 14:23 UTC, adrbounaderwiilog commented on src/Repository/ScheduledTask/ExportRepository.php
> +    private function createScheduledQueryBuilder(): QueryBuilder {
Je l'ai supprimé mais sinon non, une interface ça ne sert qu'à déclarer des trucs publics, c'est de la tembouille interne à la classe fille après
Si ya de la duplication pk pas mettre dans un trait ou transformer l'interface en class abstraite

2024-07-25 14:25 UTC, adrbounaderwiilog commented on src/Service/ScheduleRuleService.php
> +            $secondInHour = 60 * 60;
Non comme ça on comprend le calcul

2024-07-25 14:26 UTC, RobinPluviaux commented on src/Repository/ScheduledTask/ExportRepository.php
> +    private function createScheduledQueryBuilder(): QueryBuilder {
Je pensais à juste mettre la déclaration dans l'interface, mais s'il n'existe plus la question se pose plus

2024-07-26 12:38 UTC, merged