WIIS-11606
wiilog/wiistock pull request #924
Opened 2024-07-22 15:07 UTC by GregoireDolidonWiilog

2024-07-26 14:54 UTC, adrbounaderwiilog requested changes

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Service/FieldModesService.php
> +                        self::FIELD_MODE_VISIBLE => $visible,
Pas possible de mettre un sous objet avec les valeurs pour éviter le field[item.value] dans le twig
par exemple mode => [
... => boolean
]

2024-07-26 14:54 UTC, adrbounaderwiilog commented on templates/utils/fields-modes.html.twig
> +                                        {% if not  items|filter((item) => item.checked) | length %}
Sur qu'il le faut ce n'est pas prévu dans le form.switch ??

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Controller/FieldModesController.php
> +            ->map(fn(string $value) => explode(",", $value))
filterMap pour moins de tour de boucle + static

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Controller/ProductionRequest/PlanningController.php
> +                    foreach ($fields as $fieldData) {
Ne pas faire de for mais appliquer directement dans les objets

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Controller/ProductionRequest/PlanningController.php
> +                    ->map(function (ProductionRequest $productionRequest) use (&$countLinesByDate) {
faire un map sur les cards plutot que sur $productionRequests + tout map = une affectation

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Controller/ProductionRequest/PlanningController.php
> +                ->map(function (DateTime $day) use ($displayCountLines, $countLinesByDate, $planningStart, $cards, $daysWorked, $workFreeDays) {
static

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Controller/ProductionRequest/PlanningController.php
> +                    $fields = [
construction du tableau à mettre dans un service ?

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Entity/Utilisateur.php
> +    const DEFAULT_ARTICLE_FIELDS_MODES = ["actions" => [FieldModesService::FIELD_MODE_VISIBLE], "label" => [FieldModesService::FIELD_MODE_VISIBLE], "reference" => [FieldModesService::FIELD_MODE_VISIB
Tous les tableaux à indenter
Possible de les sortir et de les mettre ailleur ? mais ou ? Service

2024-07-26 14:54 UTC, adrbounaderwiilog commented on migrations/Version20240722081618.php
> +                        ->keymap(fn($column) => [
static

2024-07-26 14:54 UTC, adrbounaderwiilog commented on migrations/Version20240722081618.php
> +                            $column, [FieldModesService::FIELD_MODE_VISIBLE],
Sauter une ligne

2024-07-26 14:54 UTC, adrbounaderwiilog commented on migrations/Version20240722081618.php
> +        $this->addSql('ALTER TABLE utilisateur DROP visible_columns');
Ne pas mettre cette ligne le schema update s'en charge (ça a fait planté une migration précédemment)

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Controller/FieldModesController.php
>  #[Route("/visible-column", name: "visible_column_")]
renommer le path et le name aussi

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Controller/ProductionRequest/PlanningController.php
> +    public function index(EntityManagerInterface $entityManager, StatusService $statusService, ProductionRequestService $productionRequestService): Response {
Saut de ligne sur les paramètres

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Repository/ArticleRepository.php
> +                                if(in_array(FieldModesService::FIELD_MODE_VISIBLE, $user->getFieldModesByPage()['article'][$field] ?? [])){
On peut faire un getter qui remplace ça ? get fieldMode qui prend en param la page et le champ

2024-07-26 14:54 UTC, adrbounaderwiilog commented on src/Service/ProductionRequestService.php
> +    public function hasRigthToUpdateStatus(ProductionRequest $productionRequest):bool {
right

2024-07-29 07:45 UTC, GregoireDolidonWiilog commented on templates/utils/fields-modes.html.twig
> +{% for column in config.columns %}
Je ne veux pas modifier "config.columns", c'est pour ça que je ne fais pas de map.

2024-07-29 08:08 UTC, GregoireDolidonWiilog commented on templates/utils/fields-modes.html.twig
> +                                        {% if not  items|filter((item) => item.checked) | length %}
J'ai fait cela pour être sûr qu'il y ait au moins un switch de check. Normalement, ça n'arrive pas, car si l'utilisateur n'a pas de configuration, on passe une configuration par défaut à la modal, mais par sécurité, j'ai ajouté ça. Ça nous évite des cas particuliers.

2024-07-29 11:39 UTC, GregoireDolidonWiilog commented on assets/js/field-modes.js
> +                    $ligne.find('input[type=checkbox]').each((index, checkbox) => {
Le delete n'est pas aléatoire. Il permet de nettoyer la requête des éléments que nous ne voulons pas. Je fais un each car je suis obligé d'itérer sur tous les inputs pour le delete, donc je profite de cette itération pour push les valeurs des inputs checkés.

example de requette dans le delete() :

![image](https://github.com/user-attachments/assets/061b0859-d6f2-444b-88f7-8dfaedb689be)

2024-08-01 08:45 UTC, merged