WIIS-11685
wiilog/wiistock pull request #928
Opened 2024-07-25 13:54 UTC by RobinPluviaux

2024-07-26 08:29 UTC, adrbounaderwiilog requested changes

2024-07-26 08:29 UTC, adrbounaderwiilog commented on assets/js/pages/stock-movement/index.js
> +export function getQuantityRefArticle(refArticleId) {
mettre les fonctions exportées en premier dans le fichier

2024-07-26 08:29 UTC, adrbounaderwiilog commented on assets/js/pages/stock-movement/index.js
> +        "get_quantity_ref_article",
plutot retourner un json avec la valeur dedans stp

2024-07-26 08:29 UTC, adrbounaderwiilog commented on assets/js/pages/stock-movement/index.js
> +        .then(( qteDisponible ) => {
indentation !!

2024-07-26 08:29 UTC, adrbounaderwiilog commented on assets/js/pages/stock-movement/index.js
> +        .then(( qteDisponible ) => {
si on laisse tel quel le then n'est pas nécessaire

2024-07-26 08:29 UTC, adrbounaderwiilog commented on src/Controller/ReferenceArticleController.php
> +    #[Route("/quantite/{id}", name: "get_quantity_ref_article", options: ["expose" => true], methods: [self::GET])]
modifier la route : /{referenceArticle}/quantity plutot ? => renommer le paramettre refArticle-> referenceArticle

2024-08-06 09:30 UTC, GregoireDolidonWiilog approved these changes

2024-08-06 09:44 UTC, GregoireDolidonWiilog requested changes

2024-08-06 09:44 UTC, GregoireDolidonWiilog commented on public/js/script-wiilog.js
> +import {getQuantityRefArticle} from "@app/pages/stock-movement";
tu ne peux pas import dans un fichier qui n'est pas dans assets

2024-08-13 10:03 UTC, merged