WIIS-11783
wiilog/wiistock pull request #974
Opened 2024-08-21 07:32 UTC by GregoireDolidonWiilog

2024-08-27 12:27 UTC, adrbounaderwiilog requested changes

2024-08-27 14:45 UTC, RobinPluviaux requested changes

2024-08-27 14:45 UTC, RobinPluviaux commented on assets/js/pages/production/planning.js
> +    planningDatesForm = Form.create($planningDates);
mettre le form.create() dans une function

2024-09-16 07:29 UTC, adrbounaderwiilog approved these changes

2024-09-16 07:31 UTC, merged