WIIS-11846
wiilog/wiistock pull request #996
Opened 2024-09-02 09:03 UTC by GregoireDolidonWiilog

2024-09-04 13:51 UTC, RobinPluviaux requested changes

2024-09-04 13:51 UTC, RobinPluviaux commented on src/Service/PackService.php
> +    public function persistLogisticUnitHistoryRecord(EntityManagerInterface|UnitOfWork $entityManager,
Pourquoi ?

2024-09-09 08:51 UTC, adrbounaderwiilog commented on src/EventListener/TrackingMovementListener.php
> +                    $unitOfWork->recomputeSingleEntityChangeSet(
ça sert à quoi ici ?

2024-09-12 13:04 UTC, adrbounaderwiilog approved these changes

2024-09-12 13:04 UTC, merged